name: ci
on: [push, pull_request]
jobs:
  test-build:
    strategy:
      matrix:
        go-version: [1.23.x, 1.22.x, 1.21.x]
        # os: [ubuntu-22.04, macos-latest, windows-latest]
        # remove windows for now
        os: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Test
      run: go test -race -v -timeout 2m ./...
    - name: Build lib
      run: go build
    - name: Build cmd
      run: go build
      working-directory: ./cmd/gotail
